"""initial schema

Revision ID: 03bad674b841
Revises: 
Create Date: 2026-02-22 16:04:30.986401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03bad674b841"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("experience", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_active_at", sa.DateTime(), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("subscription_expires_at", sa.DateTime(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("timezone_changed_at", sa.DateTime(), nullable=True),
        sa.Column("streak_current", sa.Integer(), nullable=False),
        sa.Column("streak_best", sa.Integer(), nullable=False),
        sa.Column("streak_last_local_date", sa.Date(), nullable=True),
        sa.Column("delete_requested_at", sa.DateTime(), nullable=True),
        sa.Column("delete_effective_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.CheckConstraint("gender IN ('male', 'female')", name="users_gender_check"),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(op.f("ix_users_display_name"), "users", ["display_name"], unique=False, if_not_exists=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True, if_not_exists=True)

    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False, if_not_exists=True)

    op.create_table(
        "refresh_sessions",
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("rotated_from", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["rotated_from"], ["refresh_sessions.jti"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("jti"),
        if_not_exists=True,
    )
    op.create_index(op.f("ix_refresh_sessions_user_id"), "refresh_sessions", ["user_id"], unique=False, if_not_exists=True)

    op.create_table(
        "user_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plan_code", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("purchased_at", sa.DateTime(), nullable=False),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("price_cents", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )

    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("country", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        if_not_exists=True,
    )

    op.create_table(
        "songs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("original_language", sa.String(length=10), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("lyrics_text", sa.Text(), nullable=True),
        sa.Column("lyrics_text_ru", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["artist_id"], ["artists.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )

    op.create_table(
        "song_audio_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("external_url", sa.String(length=512), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )

    op.create_table(
        "track_flashcard_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("level_idx", sa.Integer(), nullable=False),
        sa.Column("kg_text", sa.Text(), nullable=False),
        sa.Column("ru_text", sa.Text(), nullable=False),
        sa.Column("order_idx", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("level_idx >= 1", name="track_flashcard_templates_level_idx_check"),
        sa.ForeignKeyConstraint(["track_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "track_id",
            "level_idx",
            "order_idx",
            "kg_text",
            name="ux_track_flashcard_templates_track_level_order_kg",
        ),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_track_flashcard_templates_track_id"),
        "track_flashcard_templates",
        ["track_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "user_track_progress",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("unlocked_level", sa.Integer(), nullable=False),
        sa.Column("unlocked_game", sa.Integer(), nullable=False),
        sa.Column("started_learning_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_listened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("status IN ('listened', 'learning', 'finished')", name="user_track_progress_status_check"),
        sa.CheckConstraint("unlocked_level >= 1", name="user_track_progress_unlocked_level_check"),
        sa.CheckConstraint("unlocked_game >= 1", name="user_track_progress_unlocked_game_check"),
        sa.ForeignKeyConstraint(["track_id"], ["songs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "track_id"),
        if_not_exists=True,
    )

    op.create_table(
        "flashcard_folders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=60), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "title", name="ux_flashcard_folders_user_title"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_flashcard_folders_user_id"),
        "flashcard_folders",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "user_track_flashcard_folder",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("folder_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["folder_id"], ["flashcard_folders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["songs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "track_id"),
        if_not_exists=True,
    )

    op.create_table(
        "track_game2_pairs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("exercise_idx", sa.Integer(), nullable=False),
        sa.Column("kg_text", sa.Text(), nullable=False),
        sa.Column("kg_text_norm", sa.String(length=500), nullable=False),
        sa.Column("ru_text", sa.Text(), nullable=False),
        sa.Column("order_idx", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("exercise_idx >= 2", name="track_game2_pairs_exercise_idx_check"),
        sa.ForeignKeyConstraint(["track_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id", "kg_text_norm", name="ux_track_game2_pairs_track_kg_norm"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_track_game2_pairs_track_id"),
        "track_game2_pairs",
        ["track_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "user_game_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("track_id", sa.Integer(), nullable=False),
        sa.Column("game_type", sa.String(length=20), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("game_type IN ('pairs')", name="user_game_sessions_game_type_check"),
        sa.CheckConstraint("level >= 1", name="user_game_sessions_level_check"),
        sa.CheckConstraint("status IN ('in_progress', 'completed', 'abandoned')", name="user_game_sessions_status_check"),
        sa.ForeignKeyConstraint(["track_id"], ["songs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_user_game_sessions_track_id"),
        "user_game_sessions",
        ["track_id"],
        unique=False,
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_user_game_sessions_user_id"),
        "user_game_sessions",
        ["user_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "user_game_answers",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("pair_id", sa.Integer(), nullable=False),
        sa.Column("chosen_option_id", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("answered_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["chosen_option_id"], ["track_game2_pairs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["pair_id"], ["track_game2_pairs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["user_game_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id", "pair_id"),
        if_not_exists=True,
    )

    op.create_table(
        "user_unlocked_songs",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("unlocked_at", sa.DateTime(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "song_id"),
        if_not_exists=True,
    )

    op.create_table(
        "user_playlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )

    op.create_table(
        "user_playlist_songs",
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["user_playlists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("playlist_id", "song_id"),
        if_not_exists=True,
    )

    op.create_table(
        "flashcards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("prompt_text", sa.Text(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("folder_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("prompt_text_norm", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(source_type = 'folder' AND folder_id IS NOT NULL AND user_id IS NOT NULL) "
            "OR (source_type IN ('curated', 'auto') AND folder_id IS NULL)",
            name="flashcards_folder_shape_check",
        ),
        sa.CheckConstraint("source_type IN ('curated', 'auto', 'folder')", name="flashcards_source_type_check"),
        sa.ForeignKeyConstraint(["folder_id"], ["flashcard_folders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("folder_id", "prompt_text_norm", name="ux_flashcards_folder_prompt_norm"),
        if_not_exists=True,
    )
    op.create_index(op.f("ix_flashcards_folder_id"), "flashcards", ["folder_id"], unique=False, if_not_exists=True)
    op.create_index(op.f("ix_flashcards_user_id"), "flashcards", ["user_id"], unique=False, if_not_exists=True)

    op.create_table(
        "user_flashcard_state",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("flashcard_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.Integer(), nullable=False),
        sa.Column("next_due_at", sa.DateTime(), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("stage >= 1", name="user_flashcard_state_stage_check"),
        sa.ForeignKeyConstraint(["flashcard_id"], ["flashcards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "flashcard_id"),
        if_not_exists=True,
    )

    op.create_table(
        "xp_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column("xp_delta", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "dedupe_key", name="ux_xp_events_user_dedupe"),
        if_not_exists=True,
    )
    op.create_index(op.f("ix_xp_events_user_id"), "xp_events", ["user_id"], unique=False, if_not_exists=True)

    op.create_table(
        "song_page_sessions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["song_id"], ["songs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "song_id"),
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("song_page_sessions", if_exists=True)
    op.drop_index(op.f("ix_xp_events_user_id"), table_name="xp_events", if_exists=True)
    op.drop_table("xp_events", if_exists=True)
    op.drop_table("user_flashcard_state", if_exists=True)
    op.drop_index(op.f("ix_flashcards_user_id"), table_name="flashcards", if_exists=True)
    op.drop_index(op.f("ix_flashcards_folder_id"), table_name="flashcards", if_exists=True)
    op.drop_table("flashcards", if_exists=True)
    op.drop_table("user_playlist_songs", if_exists=True)
    op.drop_table("user_playlists", if_exists=True)
    op.drop_table("user_unlocked_songs", if_exists=True)
    op.drop_table("user_game_answers", if_exists=True)
    op.drop_index(op.f("ix_user_game_sessions_user_id"), table_name="user_game_sessions", if_exists=True)
    op.drop_index(op.f("ix_user_game_sessions_track_id"), table_name="user_game_sessions", if_exists=True)
    op.drop_table("user_game_sessions", if_exists=True)
    op.drop_index(op.f("ix_track_game2_pairs_track_id"), table_name="track_game2_pairs", if_exists=True)
    op.drop_table("track_game2_pairs", if_exists=True)
    op.drop_table("user_track_flashcard_folder", if_exists=True)
    op.drop_index(op.f("ix_flashcard_folders_user_id"), table_name="flashcard_folders", if_exists=True)
    op.drop_table("flashcard_folders", if_exists=True)
    op.drop_table("user_track_progress", if_exists=True)
    op.drop_index(op.f("ix_track_flashcard_templates_track_id"), table_name="track_flashcard_templates", if_exists=True)
    op.drop_table("track_flashcard_templates", if_exists=True)
    op.drop_table("song_audio_sources", if_exists=True)
    op.drop_table("songs", if_exists=True)
    op.drop_table("artists", if_exists=True)
    op.drop_table("user_subscriptions", if_exists=True)
    op.drop_index(op.f("ix_refresh_sessions_user_id"), table_name="refresh_sessions", if_exists=True)
    op.drop_table("refresh_sessions", if_exists=True)
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions", if_exists=True)
    op.drop_table("sessions", if_exists=True)
    op.drop_index(op.f("ix_users_email"), table_name="users", if_exists=True)
    op.drop_index(op.f("ix_users_display_name"), table_name="users", if_exists=True)
    op.drop_table("users", if_exists=True)
    # ### end Alembic commands ###
