from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class AchievementDef:
    code: str
    title_en: str
    title_ru: str
    description_en: str
    description_ru: str
    category: str
    threshold: int
    xp_reward: int
    stat_key: str


ACHIEVEMENTS: list[AchievementDef] = [
    # ── starter ──────────────────────────────────────────────
    AchievementDef(
        code="first_lesson",
        title_en="First Steps",
        title_ru="Первые шаги",
        description_en="Complete your first lesson",
        description_ru="Завершён первый урок",
        category="starter",
        threshold=1,
        xp_reward=25,
        stat_key="songs_completed",
    ),
    AchievementDef(
        code="first_word",
        title_en="Hello, World!",
        title_ru="Салам, дүйнө!",
        description_en="Learn your first word",
        description_ru="Выучено первое слово",
        category="starter",
        threshold=1,
        xp_reward=25,
        stat_key="cards_reviewed",
    ),
    AchievementDef(
        code="first_game",
        title_en="Brave Student",
        title_ru="Смелый ученик",
        description_en="Complete your first translation exercise",
        description_ru="Выполнено первое задание на перевод",
        category="starter",
        threshold=1,
        xp_reward=25,
        stat_key="games_completed",
    ),
    # ── streak ───────────────────────────────────────────────
    AchievementDef(
        code="streak_3",
        title_en="3 Days Straight",
        title_ru="3 дня подряд",
        description_en="Study 3 days in a row",
        description_ru="Учёба без пропусков",
        category="streak",
        threshold=3,
        xp_reward=25,
        stat_key="streak_best",
    ),
    AchievementDef(
        code="streak_7",
        title_en="Week of Discipline",
        title_ru="Неделя дисциплины",
        description_en="Study 7 days in a row",
        description_ru="7 дней подряд",
        category="streak",
        threshold=7,
        xp_reward=50,
        stat_key="streak_best",
    ),
    AchievementDef(
        code="streak_14",
        title_en="14 Days of Focus",
        title_ru="14 дней фокуса",
        description_en="Study 14 days in a row",
        description_ru="2 недели подряд",
        category="streak",
        threshold=14,
        xp_reward=75,
        stat_key="streak_best",
    ),
    AchievementDef(
        code="streak_30",
        title_en="Month of Progress",
        title_ru="Месяц прогресса",
        description_en="Study 30 days in a row",
        description_ru="30 дней подряд",
        category="streak",
        threshold=30,
        xp_reward=100,
        stat_key="streak_best",
    ),
    AchievementDef(
        code="streak_60",
        title_en="Iron Habit",
        title_ru="Железная привычка",
        description_en="Study 60 days in a row",
        description_ru="60 дней подряд",
        category="streak",
        threshold=60,
        xp_reward=150,
        stat_key="streak_best",
    ),
    # ── vocabulary ───────────────────────────────────────────
    AchievementDef(
        code="vocab_10",
        title_en="10 Words",
        title_ru="10 слов",
        description_en="Learn 10 words",
        description_ru="Выучено 10 слов",
        category="vocabulary",
        threshold=10,
        xp_reward=25,
        stat_key="cards_reviewed",
    ),
    AchievementDef(
        code="vocab_50",
        title_en="50 Words",
        title_ru="50 слов",
        description_en="Learn 50 words",
        description_ru="Выучено 50 слов",
        category="vocabulary",
        threshold=50,
        xp_reward=50,
        stat_key="cards_reviewed",
    ),
    AchievementDef(
        code="vocab_100",
        title_en="100 Words",
        title_ru="100 слов",
        description_en="Learn 100 words",
        description_ru="Выучено 100 слов",
        category="vocabulary",
        threshold=100,
        xp_reward=75,
        stat_key="cards_reviewed",
    ),
    AchievementDef(
        code="vocab_250",
        title_en="250 Words",
        title_ru="250 слов",
        description_en="Learn 250 words",
        description_ru="Выучено 250 слов",
        category="vocabulary",
        threshold=250,
        xp_reward=100,
        stat_key="cards_reviewed",
    ),
    AchievementDef(
        code="vocab_500",
        title_en="500 Words",
        title_ru="500 слов",
        description_en="Learn 500 words",
        description_ru="Выучено 500 слов",
        category="vocabulary",
        threshold=500,
        xp_reward=150,
        stat_key="cards_reviewed",
    ),
    # ── xp ───────────────────────────────────────────────────
    AchievementDef(
        code="xp_50",
        title_en="Beginner",
        title_ru="Начинающий",
        description_en="Earn 50 XP",
        description_ru="Получить 50 XP",
        category="xp",
        threshold=50,
        xp_reward=25,
        stat_key="total_xp",
    ),
    AchievementDef(
        code="xp_150",
        title_en="Greeted",
        title_ru="Поздоровался",
        description_en="Earn 150 XP",
        description_ru="Получить 150 XP",
        category="xp",
        threshold=150,
        xp_reward=25,
        stat_key="total_xp",
    ),
    AchievementDef(
        code="xp_300",
        title_en="First Step",
        title_ru="Первый шаг",
        description_en="Earn 300 XP",
        description_ru="Получить 300 XP",
        category="xp",
        threshold=300,
        xp_reward=50,
        stat_key="total_xp",
    ),
    AchievementDef(
        code="xp_500",
        title_en="Student",
        title_ru="Ученик",
        description_en="Earn 500 XP",
        description_ru="Получить 500 XP",
        category="xp",
        threshold=500,
        xp_reward=50,
        stat_key="total_xp",
    ),
    AchievementDef(
        code="xp_800",
        title_en="Active Student",
        title_ru="Активный ученик",
        description_en="Earn 800 XP",
        description_ru="Получить 800 XP",
        category="xp",
        threshold=800,
        xp_reward=75,
        stat_key="total_xp",
    ),
    # ── songs ────────────────────────────────────────────────
    AchievementDef(
        code="songs_3",
        title_en="3 Songs Opened",
        title_ru="3 песни открыто",
        description_en="Open 3 songs",
        description_ru="Открыть 3 песни",
        category="songs",
        threshold=3,
        xp_reward=25,
        stat_key="songs_completed",
    ),
    AchievementDef(
        code="songs_5",
        title_en="Musical Five",
        title_ru="Музыкальная пятёрка",
        description_en="Open 5 songs",
        description_ru="Открыть 5 песен",
        category="songs",
        threshold=5,
        xp_reward=50,
        stat_key="songs_completed",
    ),
    AchievementDef(
        code="songs_10",
        title_en="10 Tracks",
        title_ru="10 треков",
        description_en="Open 10 songs",
        description_ru="Открыть 10 песен",
        category="songs",
        threshold=10,
        xp_reward=75,
        stat_key="songs_completed",
    ),
    AchievementDef(
        code="songs_20",
        title_en="20 Songs",
        title_ru="20 песен",
        description_en="Open 20 songs",
        description_ru="Открыть 20 песен",
        category="songs",
        threshold=20,
        xp_reward=100,
        stat_key="songs_completed",
    ),
    # ── perfect ──────────────────────────────────────────────
    AchievementDef(
        code="perfect_3",
        title_en="Perfect Rhythm",
        title_ru="Идеальный ритм",
        description_en="Complete 3 levels without mistakes",
        description_ru="Пройти 3 уровня без ошибок",
        category="perfect",
        threshold=3,
        xp_reward=25,
        stat_key="perfect_games",
    ),
    AchievementDef(
        code="perfect_5",
        title_en="Flawless Series",
        title_ru="Безупречная серия",
        description_en="Complete 5 levels without mistakes",
        description_ru="5 уровней без ошибок",
        category="perfect",
        threshold=5,
        xp_reward=50,
        stat_key="perfect_games",
    ),
    AchievementDef(
        code="perfect_10",
        title_en="Absolute Precision",
        title_ru="Абсолютная точность",
        description_en="Complete 10 levels without mistakes",
        description_ru="10 уровней без ошибок",
        category="perfect",
        threshold=10,
        xp_reward=75,
        stat_key="perfect_games",
    ),
    AchievementDef(
        code="perfect_20",
        title_en="Master Marksman",
        title_ru="Мастер без промаха",
        description_en="Complete 20 levels without mistakes",
        description_ru="Пройти 20 уровней без ошибок",
        category="perfect",
        threshold=20,
        xp_reward=100,
        stat_key="perfect_games",
    ),
    AchievementDef(
        code="perfect_30",
        title_en="Perfect Path",
        title_ru="Совершенный путь",
        description_en="Complete 30 levels without mistakes",
        description_ru="30 уровней без ошибок",
        category="perfect",
        threshold=30,
        xp_reward=150,
        stat_key="perfect_games",
    ),
]

ACHIEVEMENTS_BY_CODE: dict[str, AchievementDef] = {a.code: a for a in ACHIEVEMENTS}
